name: Cybersecurity Chatbot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Enables manual triggering

env:
  DOTNET_VERSION: '6.0.x'
  RUNTIME_ID: 'win10-x64'
  PUBLISH_DIR: './publish'

jobs:
  validate:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify audio file
      run: |
        if (-not (Test-Path -Path "welcome.wav")) {
          Write-Output "::warning::Audio file welcome.wav not found. Default greeting will be used."
        } else {
          Write-Output "Audio file verified successfully"
        }

  build-and-test:
    needs: validate
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish application
      run: dotnet publish -c Release -r ${{ env.RUNTIME_ID }} --self-contained false -o ${{ env.PUBLISH_DIR }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: chatbot-${{ github.run_number }}
        path: |
          ${{ env.PUBLISH_DIR }}/
          welcome.wav

  release:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: chatbot-${{ github.run_number }}

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          Cybersecurity Awareness Chatbot
          - Version: 1.0.${{ github.run_number }}
          - Build Date: ${{ steps.get-date.outputs.date }}
          Changes:
          ${{ github.event.head_commit.message }}
        files: |
          ${{ env.PUBLISH_DIR }}/*.exe
          ${{ env.PUBLISH_DIR }}/*.dll
          ${{ env.PUBLISH_DIR }}/*.json
          welcome.wav
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current date
      id: get-date
      run: echo "date=$(date)" >> $GITHUB_OUTPUT
