# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: Cybersecurity Chatbot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest  # Required for System.Media.SoundPlayer

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Or your target version

    - name: Verify audio file exists
      run: |
        if (-not (Test-Path -Path "welcome.wav")) {
          Write-Output "::warning file=welcome.wav::Audio file not found. Default greeting will be used."
        }

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish application
      run: dotnet publish -c Release -r win10-x64 --self-contained false -o ./publish

    - name: Create release artifact
      uses: actions/upload-artifact@v3
      with:
        name: cybersecurity-chatbot
        path: |
          ./publish/
          ./welcome.wav
        if-no-files-found: error

  release:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: windows-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: cybersecurity-chatbot

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          publish/*.exe
          publish/*.dll
          publish/*.json
          welcome.wav
        body: "Cybersecurity Awareness Chatbot - Windows Desktop Application"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
